"""Collect M4 evaluation outputs into comparison tables.

Reads <root>/<eval dir>/<model>/<set>/metrics.json and .../sequences/blast_tracks.json
from every evaluation directory under results/m4_experiments (parallel workers wrote
to separate directories) and writes results/m4_experiments/tables.md and tables.json.

    uv run python scripts/m4_tables.py
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1] / "results" / "m4_experiments"

MODELS = [  # (key, label, training data, labels used in training, recipe, serving)
    ("m3_local", "M3 local", "v1", "correct", "local", "PyTorch"),
    ("m3_hosted", "M3 hosted", "v1", "platform-stored", "hosted", "inference (ONNX)"),
    ("arm_A_hosted_recipe", "A: hosted recipe", "v1", "correct", "hosted settings, local",
     "PyTorch"),
    ("arm_B_v2_data", "B: v2 data", "v2", "correct", "local", "PyTorch"),
    ("arm_C_vec_encoding", "C: vector encoding", "v1", "correct", "local", "PyTorch"),
    ("arm_D_platform_labels", "D: platform labels (20 ep)", "v2", "platform-stored", "local",
     "PyTorch"),
    ("v2_hosted", "v2 hosted", "v2", "platform-stored", "hosted", "inference (ONNX)"),
    ("v2_hosted_weights_pytorch", "v2 hosted weights", "v2", "platform-stored", "hosted",
     "PyTorch"),
]
SETS = ["v1_test", "control", "estimator_farneback", "estimator_demons", "camera_harsh",
        "optics_shift", "physics_extrapolation", "composite"]


def collect() -> dict:
    out: dict = {}
    for eval_dir in sorted(p for p in ROOT.iterdir() if p.is_dir() and p.name.startswith("eval")):
        for model_dir in eval_dir.iterdir():
            if not model_dir.is_dir():
                continue
            m = out.setdefault(model_dir.name, {})
            for set_dir in model_dir.iterdir():
                f = set_dir / "metrics.json"
                if f.exists() and set_dir.name not in m:
                    m[set_dir.name] = json.loads(f.read_text())
                b = set_dir / "blast_tracks.json"
                if b.exists() and "blast" not in m:
                    m["blast"] = blast_summary(json.loads(b.read_text()))
    return out


def blast_summary(tracks: list[dict]) -> dict:
    s = {}
    for v in ("raw", "gated"):
        d = [t[v] for t in tracks if "exponent" in t.get(v, {})]
        if d:
            s[v] = {"exponent_mean": float(np.mean([x["exponent"] for x in d])),
                    "exponent_std": float(np.std([x["exponent"] for x in d])),
                    "E_err_worst": float(max(abs(x["E_rel_err"]) for x in d)),
                    "n_bad": sum(abs(x["E_rel_err"]) > 0.1 for x in d),
                    "n": len(d)}
    return s


def fmt(x, pct=False):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "n/a"
    return f"{100 * x:.1f}%" if pct else f"{x:.3f}"


def main():
    data = collect()
    lines = ["# M4 comparison tables", "",
             "Generated by `scripts/m4_tables.py` from the per-set result files.", ""]
    lines += ["## Models", "", "| model | training data | training labels | recipe | serving |",
              "|---|---|---|---|---|"]
    lines += [f"| {lab} | {d} | {lb} | {rc} | {sv} |" for _, lab, d, lb, rc, sv in MODELS]

    lines += ["", "## v1 test split (100 images): mask mAP and Mach recovery", "",
              ("| model | mAP50-95 | mAP50 | shock | expansion fan | shear layer | "
               "wedge Mach err | cone Mach err |"), "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for key, lab, *_ in MODELS:
        r = data.get(key, {}).get("v1_test")
        if not r:
            continue
        lines.append(f"| {lab} | {fmt(r['mAP50_95'])} | {fmt(r['mAP50'])} | "
                     f"{fmt(r.get('AP50_95_shock'))} | {fmt(r.get('AP50_95_expansion_fan'))} | "
                     f"{fmt(r.get('AP50_95_shear_layer'))} | "
                     f"{fmt(r.get('wedge_mach_rel_err_median'), True)} | "
                     f"{fmt(r.get('cone_mach_rel_err_median'), True)} |")

    lines += ["", "## Blast fronts through 20 sequences (Sedov-Taylor exponent 0.4)", "",
              ("| model | raw exponent | raw worst E error | raw sequences > 10% | "
               "gated exponent | gated worst E error |"), "|---|---:|---:|---:|---:|---:|"]
    for key, lab, *_ in MODELS:
        b = data.get(key, {}).get("blast")
        if not b:
            continue
        r, g = b.get("raw", {}), b.get("gated", {})
        lines.append(f"| {lab} | {r.get('exponent_mean', 0):.4f} +- {r.get('exponent_std', 0):.4f}"
                     f" | {fmt(r.get('E_err_worst'), True)} | {r.get('n_bad')}/{r.get('n')} | "
                     f"{g.get('exponent_mean', 0):.4f} +- {g.get('exponent_std', 0):.4f} | "
                     f"{fmt(g.get('E_err_worst'), True)} |")

    lines += ["", "## Stress tests: mask mAP50-95 by set", "",
              "| model | " + " | ".join(SETS) + " |", "|---|" + "---:|" * len(SETS)]
    for key, lab, *_ in MODELS:
        row = data.get(key, {})
        if not any(s in row for s in SETS[1:]):
            continue
        lines.append(f"| {lab} | " + " | ".join(
            fmt(row[s]["mAP50_95"]) if s in row else "n/a" for s in SETS) + " |")

    lines += ["", "## Stress tests: shock mask AP50-95 by set", "",
              "| model | " + " | ".join(SETS) + " |", "|---|" + "---:|" * len(SETS)]
    for key, lab, *_ in MODELS:
        row = data.get(key, {})
        if not any(s in row for s in SETS[1:]):
            continue
        lines.append(f"| {lab} | " + " | ".join(
            fmt(row[s].get("AP50_95_shock")) if s in row else "n/a" for s in SETS) + " |")

    (ROOT / "tables.md").write_text("\n".join(lines) + "\n")
    (ROOT / "tables.json").write_text(json.dumps(data, indent=1, default=float))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
